name: Check formatting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    env:
      FORMATTER_VERSION: 1.22.0

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up JDK 13
        uses: actions/setup-java@v3
        with:
          java-version: '13'
          distribution: 'zulu'
      - name: Download formatter
        run: |
          URL="https://github.com/google/google-java-format/releases/download/v$FORMATTER_VERSION/google-java-format-$FORMATTER_VERSION-all-deps.jar"
          wget $URL -O $RUNNER_TEMP/formatter.jar --no-verbose
      - name: Check formatting
        run: |
          # Format checking script:
          # Enable globstar to allow recursive searching
          shopt -s globstar
          # Run the formatter (and print an error message on failure)
          java -jar $RUNNER_TEMP/formatter.jar --dry-run --set-exit-if-changed --aosp ./**/*.java \
            || { echo "The above file(s) failed the formatting check!"; exit 1; }